name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t tax-prediction-api .
      
    - name: Start API container
      run: |
        docker run -d -p 8000:8000 --name tax-api tax-prediction-api
        sleep 30  # Wait for container to start

        # Check if container is running and show logs
        docker ps
        docker logs tax-api
        
    - name: Check API health
      run: |
        response=$(curl -s http://localhost:8000/health)
        if [[ $response == *"ok"* ]]; then
          echo "API is healthy"
        else
          echo "API health check failed"
          exit 1
        fi
        
    - name: Run tests in container
      run: |
        docker exec tax-api pytest -v
        
    - name: Test prediction endpoint
      run: |
        curl -X POST http://localhost:8000/predict \
          -H "Content-Type: application/json" \
          -d '{
              "age": 12,
              "income": 75000.5,
              "employment_type": "full_time",
              "marital_status": "married",
              "time_spent_on_platform": 210.5,
              "number_of_sessions": 22,
              "fields_filled_percentage": 95.2,
              "previous_year_filing": 0,
              "device_type": "desktop",
              "referral_source": "organic_search"
          }'

    - name: Test retrain endpoint
      run: |
        curl -X POST http://localhost:8000/retrain \
          -H "Content-Type: application/json" \
          -d '{
              "data_path": "/app/data/dataset.csv"
          }'

    - name: Test prediction endpoint
      run: |
        curl -X POST http://localhost:8000/predict \
          -H "Content-Type: application/json" \
          -d '{
              "age": 12,
              "income": 75000.5,
              "employment_type": "full_time",
              "marital_status": "married",
              "time_spent_on_platform": 210.5,
              "number_of_sessions": 22,
              "fields_filled_percentage": 95.2,
              "previous_year_filing": 0,
              "device_type": "desktop",
              "referral_source": "organic_search"
          }'
                      
    - name: Cleanup
      run: docker stop tax-api